DATA UNDERSTANDINGG

In [1]:
# =====================================
# Data Quality Assessment
# =====================================

import pandas as pd
import numpy as np

pd.set_option("display.max_columns",None)

df = pd.read_csv("../data/raw/Personalized_Diet_Recommendations.csv")

print(df.shape)

(5000, 30)

In [2]:
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().sum()/len(df))*100
})

missing = missing[missing["Missing Values"]>0]

missing.sort_values("Percentage",ascending=False)

                 Missing Values  Percentage
Allergies                  3497       69.94
Chronic_Disease            2043       40.86
Food_Aversions             1225       24.50

In [3]:
duplicates = df.duplicated().sum()

print(f"Duplicate Rows : {duplicates}")

Duplicate Rows : 0

In [4]:
df["Patient_ID"].nunique()

5000

In [5]:
df[df["Age"]<0]
df[df["Age"]>120]

Empty DataFrame
Columns: [Patient_ID, Age, Gender, Height_cm, Weight_kg, BMI, Chronic_Disease, Blood_Pressure_Systolic, Blood_Pressure_Diastolic, Cholesterol_Level, Blood_Sugar_Level, Genetic_Risk_Factor, Allergies, Daily_Steps, Exercise_Frequency, Sleep_Hours, Alcohol_Consumption, Smoking_Habit, Dietary_Habits, Caloric_Intake, Protein_Intake, Carbohydrate_Intake, Fat_Intake, Preferred_Cuisine, Food_Aversions, Recommended_Calories, Recommended_Protein, Recommended_Carbs, Recommended_Fats, Recommended_Meal_Plan]
Index: []

In [6]:
df["Height_cm"].describe()

count    5000.000000
mean      174.244000
std        14.229173
min       150.000000
25%       162.000000
50%       174.000000
75%       186.000000
max       199.000000
Name: Height_cm, dtype: float64

In [7]:
df["Weight_kg"].describe()

count    5000.00000
mean       84.36620
std        20.18103
min        50.00000
25%        67.00000
50%        84.00000
75%       102.00000
max       119.00000
Name: Weight_kg, dtype: float64

In [8]:
df["BMI"].describe()

count    5000.000000
mean       28.353134
std         8.297745
min        12.630000
25%        21.850000
50%        27.640000
75%        33.812500
max        52.890000
Name: BMI, dtype: float64

In [9]:
df["Blood_Pressure_Systolic"].describe()

df["Blood_Pressure_Diastolic"].describe()

count    5000.000000
mean       89.735800
std        17.283025
min        60.000000
25%        75.000000
50%        90.000000
75%       105.000000
max       119.000000
Name: Blood_Pressure_Diastolic, dtype: float64

In [10]:
df["Blood_Sugar_Level"].describe()

count    5000.00000
mean      159.33020
std        52.14943
min        70.00000
25%       114.00000
50%       160.00000
75%       204.00000
max       249.00000
Name: Blood_Sugar_Level, dtype: float64

In [11]:
df["Cholesterol_Level"].describe()

count    5000.000000
mean      224.297800
std        42.918923
min       150.000000
25%       187.000000
50%       224.000000
75%       261.000000
max       299.000000
Name: Cholesterol_Level, dtype: float64

In [12]:
for col in df.select_dtypes(include="object"):

    print("="*60)

    print(col)

    print(df[col].value_counts(dropna=False))

============================================================
Patient_ID
Patient_ID
P00001    1
P00002    1
P00003    1
P00004    1
P00005    1
         ..
P04996    1
P04997    1
P04998    1
P04999    1
P05000    1
Name: count, Length: 5000, dtype: int64
============================================================
Gender
Gender
Female    1695
Other     1653
Male      1652
Name: count, dtype: int64
============================================================
Chronic_Disease
Chronic_Disease
NaN              2043
Diabetes         1019
Heart Disease     749
Hypertension      693
Obesity           496
Name: count, dtype: int64
============================================================
Genetic_Risk_Factor
Genetic_Risk_Factor
No     3472
Yes    1528
Name: count, dtype: int64
============================================================
Allergies
Allergies
NaN                    3497
Lactose Intolerance     556
Nut Allergy             483
Gluten Intolerance      464
Name: count, dtype: int64
============================================================
Alcohol_Consumption
Alcohol_Consumption
No     3509
Yes    1491
Name: count, dtype: int64
============================================================
Smoking_Habit
Smoking_Habit
No     4025
Yes     975
Name: count, dtype: int64
============================================================
Dietary_Habits
Dietary_Habits
Regular       2498
Keto          1006
Vegetarian    1001
Vegan          495
Name: count, dtype: int64
============================================================
Preferred_Cuisine
Preferred_Cuisine
Asian            1259
Indian           1259
Western          1257
Mediterranean    1225
Name: count, dtype: int64
============================================================
Food_Aversions
Food_Aversions
Spicy    1263
Sweet    1262
Salty    1250
NaN      1225
Name: count, dtype: int64
============================================================
Recommended_Meal_Plan
Recommended_Meal_Plan
Low-Fat Diet         1313
High-Protein Diet    1255
Balanced Diet        1250
Low-Carb Diet        1182
Name: count, dtype: int64

# Data Quality Assessment Report

## Dataset Quality

✔ No duplicate records

✔ Unique patient identifiers

✔ No invalid data types

✔ Numerical columns are within expected medical ranges

✔ Categorical values are consistent

## Missing Data

The missing values appear to represent the absence of medical conditions rather than incomplete records.

Therefore,

- Missing values in Chronic_Disease will later be replaced with "No Disease".

- Missing values in Allergies will later be replaced with "None".

- Missing values in Food_Aversions will later be replaced with "None".

No rows need to be removed because of missing values.

DATA CLEANING

# Notebook 02 – Data Cleaning

## Objective

The purpose of this notebook is to prepare the patient dataset for machine learning by performing data cleaning and preprocessing.

### Tasks Performed

- Load the dataset
- Assess data quality
- Handle missing values
- Remove unnecessary columns
- Standardize categorical values
- Verify the cleaned dataset
- Save the cleaned dataset for further analysis

### Input

`data/raw/Personalized_Diet_Recommendations.csv`

### Output

`data/processed/cleaned_patient_dataset.csv`

## Step 1 – Import Required Libraries

In [13]:
# ==========================================
# Import Required Libraries
# ==========================================

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

print("Libraries imported successfully.")

Libraries imported successfully.

## Step 2 – Load the Raw Dataset

In [14]:
# ==========================================
# Load Dataset
# ==========================================

df = pd.read_csv("../data/raw/Personalized_Diet_Recommendations.csv")

print("Dataset Loaded Successfully!")

print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

df.head()

Dataset Loaded Successfully!
Rows    : 5000
Columns : 30

,Patient_ID,Age,Gender,Height_cm,Weight_kg,BMI,Chronic_Disease,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Cholesterol_Level,Blood_Sugar_Level,Genetic_Risk_Factor,Allergies,Daily_Steps,Exercise_Frequency,Sleep_Hours,Alcohol_Consumption,Smoking_Habit,Dietary_Habits,Caloric_Intake,Protein_Intake,Carbohydrate_Intake,Fat_Intake,Preferred_Cuisine,Food_Aversions,Recommended_Calories,Recommended_Protein,Recommended_Carbs,Recommended_Fats,Recommended_Meal_Plan
0,P00001,56,Other,163,66,24.84,NaN,175,75,219,124,No,NaN,11452,5,7.6,No,Yes,Vegetarian,2593,105,179,143,Western,NaN,2150,108,139,145,High-Protein Diet
1,P00002,69,Female,171,114,38.99,NaN,155,72,208,72,No,NaN,12962,1,6.3,Yes,No,Vegetarian,1852,69,315,75,Mediterranean,NaN,1527,74,266,80,Balanced Diet
2,P00003,46,Female,172,119,40.22,NaN,137,101,171,145,No,Gluten Intolerance,7898,3,9.9,No,No,Vegetarian,2737,183,103,148,Western,Sweet,2359,180,145,143,High-Protein Diet
3,P00004,32,Female,197,118,30.41,NaN,148,91,258,235,No,Nut Allergy,6602,5,4.2,No,No,Vegetarian,3289,135,371,120,Western,NaN,2858,137,378,135,High-Protein Diet
4,P00005,60,Female,156,109,44.79,Hypertension,160,109,260,248,Yes,NaN,9810,2,9.0,No,No,Regular,2405,167,298,48,Indian,Spicy,1937,166,317,56,High-Protein Diet

## Step 3 – Data Quality Assessment

Before cleaning the data, we examine:

- Missing values
- Duplicate rows
- Data types
- Dataset structure

This helps determine the appropriate preprocessing strategy.

In [15]:
# ==========================================
# Missing Values
# ==========================================

missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage (%)": round(df.isnull().sum()/len(df)*100,2)
})

missing = missing[missing["Missing Values"]>0]

missing.sort_values("Percentage (%)",ascending=False)

                 Missing Values  Percentage (%)
Allergies                  3497           69.94
Chronic_Disease            2043           40.86
Food_Aversions             1225           24.50

In [16]:
# ==========================================
# Duplicate Records
# ==========================================

duplicates = df.duplicated().sum()

print(f"Duplicate Records : {duplicates}")

Duplicate Records : 0

In [17]:
# ==========================================
# Data Types
# ==========================================

df.dtypes

Patient_ID                   object
Age                           int64
Gender                       object
Height_cm                     int64
Weight_kg                     int64
BMI                         float64
Chronic_Disease              object
Blood_Pressure_Systolic       int64
Blood_Pressure_Diastolic      int64
Cholesterol_Level             int64
Blood_Sugar_Level             int64
Genetic_Risk_Factor          object
Allergies                    object
Daily_Steps                   int64
Exercise_Frequency            int64
Sleep_Hours                 float64
Alcohol_Consumption          object
Smoking_Habit                object
Dietary_Habits               object
Caloric_Intake                int64
Protein_Intake                int64
Carbohydrate_Intake           int64
Fat_Intake                    int64
Preferred_Cuisine            object
Food_Aversions               object
Recommended_Calories          int64
Recommended_Protein           int64
Recommended_Carbs             int64
Recommended_Fats              int64
Recommended_Meal_Plan        object
dtype: object

## Step 4 – Create a Working Copy

The original dataset is preserved by creating a copy before applying any transformations.

In [18]:
clean_df = df.copy()

print("Working copy created successfully.")

Working copy created successfully.

## Step 5 – Remove Non-Predictive Features

The `Patient_ID` column is a unique identifier and does not contribute to prediction. It is removed before model training.

In [19]:
clean_df.drop(columns=["Patient_ID"], inplace=True)

print("Patient_ID removed.")

print(clean_df.shape)

Patient_ID removed.
(5000, 29)

## Step 6 – Handle Missing Values

The missing values represent the absence of a condition rather than missing information.

Therefore:

- Chronic_Disease → "No Disease"
- Allergies → "None"
- Food_Aversions → "None"

In [20]:
clean_df["Chronic_Disease"] = clean_df["Chronic_Disease"].fillna("No Disease")

clean_df["Allergies"] = clean_df["Allergies"].fillna("None")

clean_df["Food_Aversions"] = clean_df["Food_Aversions"].fillna("None")

In [21]:
clean_df.isnull().sum()

Age                         0
Gender                      0
Height_cm                   0
Weight_kg                   0
BMI                         0
Chronic_Disease             0
Blood_Pressure_Systolic     0
Blood_Pressure_Diastolic    0
Cholesterol_Level           0
Blood_Sugar_Level           0
Genetic_Risk_Factor         0
Allergies                   0
Daily_Steps                 0
Exercise_Frequency          0
Sleep_Hours                 0
Alcohol_Consumption         0
Smoking_Habit               0
Dietary_Habits              0
Caloric_Intake              0
Protein_Intake              0
Carbohydrate_Intake         0
Fat_Intake                  0
Preferred_Cuisine           0
Food_Aversions              0
Recommended_Calories        0
Recommended_Protein         0
Recommended_Carbs           0
Recommended_Fats            0
Recommended_Meal_Plan       0
dtype: int64

## Step 7 – Standardize Categorical Values

Leading and trailing spaces are removed from all categorical features to ensure consistency.

In [22]:
categorical_columns = clean_df.select_dtypes(include="object").columns

for col in categorical_columns:
    clean_df[col] = clean_df[col].str.strip()

## Step 8 – Verify the Cleaned Dataset

In [23]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 29 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       5000 non-null   int64
 1   Gender                    5000 non-null   object
 2   Height_cm                 5000 non-null   int64
 3   Weight_kg                 5000 non-null   int64
 4   BMI                       5000 non-null   float64
 5   Chronic_Disease           5000 non-null   object
 6   Blood_Pressure_Systolic   5000 non-null   int64
 7   Blood_Pressure_Diastolic  5000 non-null   int64
 8   Cholesterol_Level         5000 non-null   int64
 9   Blood_Sugar_Level         5000 non-null   int64
 10  Genetic_Risk_Factor       5000 non-null   object
 11  Allergies                 5000 non-null   object
 12  Daily_Steps               5000 non-null   int64
 13  Exercise_Frequency        5000 non-null   int64
 14  Sleep_Hours               5000 non-null   float64
 15  Alcohol_Consumption       5000 non-null   object
 16  Smoking_Habit             5000 non-null   object
 17  Dietary_Habits            5000 non-null   object
 18  Caloric_Intake            5000 non-null   int64
 19  Protein_Intake            5000 non-null   int64
 20  Carbohydrate_Intake       5000 non-null   int64
 21  Fat_Intake                5000 non-null   int64
 22  Preferred_Cuisine         5000 non-null   object
 23  Food_Aversions            5000 non-null   object
 24  Recommended_Calories      5000 non-null   int64
 25  Recommended_Protein       5000 non-null   int64
 26  Recommended_Carbs         5000 non-null   int64
 27  Recommended_Fats          5000 non-null   int64
 28  Recommended_Meal_Plan     5000 non-null   object
dtypes: float64(2), int64(17), object(10)
memory usage: 1.1+ MB

In [24]:
print(clean_df.head())
print(clean_df.shape)

   Age  Gender  Height_cm  Weight_kg    BMI Chronic_Disease  \
0   56   Other        163         66  24.84      No Disease
1   69  Female        171        114  38.99      No Disease
2   46  Female        172        119  40.22      No Disease
3   32  Female        197        118  30.41      No Disease
4   60  Female        156        109  44.79    Hypertension

   Blood_Pressure_Systolic  Blood_Pressure_Diastolic  Cholesterol_Level  \
0                      175                        75                219
1                      155                        72                208
2                      137                       101                171
3                      148                        91                258
4                      160                       109                260

   Blood_Sugar_Level Genetic_Risk_Factor           Allergies  Daily_Steps  \
0                124                  No                None        11452
1                 72                  No                None        12962
2                145                  No  Gluten Intolerance         7898
3                235                  No         Nut Allergy         6602
4                248                 Yes                None         9810

   Exercise_Frequency  Sleep_Hours Alcohol_Consumption Smoking_Habit  \
0                   5          7.6                  No           Yes
1                   1          6.3                 Yes            No
2                   3          9.9                  No            No
3                   5          4.2                  No            No
4                   2          9.0                  No            No

  Dietary_Habits  Caloric_Intake  Protein_Intake  Carbohydrate_Intake  \
0     Vegetarian            2593             105                  179
1     Vegetarian            1852              69                  315
2     Vegetarian            2737             183                  103
3     Vegetarian            3289             135                  371
4        Regular            2405             167                  298

   Fat_Intake Preferred_Cuisine Food_Aversions  Recommended_Calories  \
0         143           Western           None                  2150
1          75     Mediterranean           None                  1527
2         148           Western          Sweet                  2359
3         120           Western           None                  2858
4          48            Indian          Spicy                  1937

   Recommended_Protein  Recommended_Carbs  Recommended_Fats  \
0                  108                139               145
1                   74                266                80
2                  180                145               143
3                  137                378               135
4                  166                317                56

  Recommended_Meal_Plan
0     High-Protein Diet
1         Balanced Diet
2     High-Protein Diet
3     High-Protein Diet
4     High-Protein Diet
(5000, 29)

## Step 9 – Save the Cleaned Dataset

In [25]:
clean_df.to_csv(
    "../data/processed/cleaned_patient_dataset.csv",
    index=False
)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [26]:
verification = pd.read_csv(
    "../data/processed/cleaned_patient_dataset.csv"
)

verification.head()

,Age,Gender,Height_cm,Weight_kg,BMI,Chronic_Disease,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Cholesterol_Level,Blood_Sugar_Level,Genetic_Risk_Factor,Allergies,Daily_Steps,Exercise_Frequency,Sleep_Hours,Alcohol_Consumption,Smoking_Habit,Dietary_Habits,Caloric_Intake,Protein_Intake,Carbohydrate_Intake,Fat_Intake,Preferred_Cuisine,Food_Aversions,Recommended_Calories,Recommended_Protein,Recommended_Carbs,Recommended_Fats,Recommended_Meal_Plan
0,56,Other,163,66,24.84,No Disease,175,75,219,124,No,NaN,11452,5,7.6,No,Yes,Vegetarian,2593,105,179,143,Western,NaN,2150,108,139,145,High-Protein Diet
1,69,Female,171,114,38.99,No Disease,155,72,208,72,No,NaN,12962,1,6.3,Yes,No,Vegetarian,1852,69,315,75,Mediterranean,NaN,1527,74,266,80,Balanced Diet
2,46,Female,172,119,40.22,No Disease,137,101,171,145,No,Gluten Intolerance,7898,3,9.9,No,No,Vegetarian,2737,183,103,148,Western,Sweet,2359,180,145,143,High-Protein Diet
3,32,Female,197,118,30.41,No Disease,148,91,258,235,No,Nut Allergy,6602,5,4.2,No,No,Vegetarian,3289,135,371,120,Western,NaN,2858,137,378,135,High-Protein Diet
4,60,Female,156,109,44.79,Hypertension,160,109,260,248,Yes,NaN,9810,2,9.0,No,No,Regular,2405,167,298,48,Indian,Spicy,1937,166,317,56,High-Protein Diet

# Conclusion

The dataset has been successfully cleaned and prepared for further analysis.

Cleaning steps completed:

- Removed Patient_ID
- Filled missing values
- Standardized categorical variables
- Verified data integrity
- Saved cleaned dataset

The cleaned dataset will be used for Exploratory Data Analysis (EDA) in the next notebook.

In [27]:
cleaning_report = {
    "Original Rows": len(df),
    "Original Columns": df.shape[1],
    "Cleaned Rows": len(clean_df),
    "Cleaned Columns": clean_df.shape[1],
    "Removed Columns": ["Patient_ID"],
    "Filled Missing Values": {
        "Chronic_Disease": "No Disease",
        "Allergies": "None",
        "Food_Aversions": "None"
    }
}

import json

with open("../reports/metrics/data_cleaning_report.json", "w") as f:
    json.dump(cleaning_report, f, indent=4)

print("Data cleaning report saved successfully.")

Data cleaning report saved successfully.